# Compute Node - Nova 설정
# 실제 VM을 실행하는 노드
# nova-compute 단일 컴포넌트만 설치

[DEFAULT]
my_ip = 10.0.0.20
auth_strategy = keystone
transport_url = rabbit://openstack:openstack@10.0.0.10:5672/

[keystone_authtoken]
www_authenticate_uri = http://10.0.0.10:5000/
auth_url = http://10.0.0.10:5000/v3
memcached_servers = 10.0.0.10:11211
auth_type = password
project_domain_name = Default
user_domain_name = Default
project_name = service
username = nova
password = nova

[glance]
api_servers = http://10.0.0.10:9292

[placement]
region_name = RegionOne
project_domain_name = Default
project_name = service
auth_type = password
user_domain_name = Default
auth_url = http://10.0.0.10:5000/v3
username = placement
password = placement

[vnc]
enabled = true
server_listen = 0.0.0.0
server_proxyclient_address = $my_ip
novncproxy_base_url = http://192.168.0.10:6080/vnc_auto.html

[oslo_concurrency]
lock_path = /var/lib/nova/tmp

# KVM 하이퍼바이저 드라이버 설정
# CPU 가상화 확장 기능(vmx/svm) 확인 후 kvm / qemu 선택
[libvirt]
virt_type = kvm
