# Controller Node - Placement 설정
# 클러스터 내 CPU / RAM / Disk 등 물리 자원 현황 추적
# Nova 스케줄러가 VM 배치 시 최적 노드 선정에 사용

[database]
connection = mysql+pymysql://placement:placement@10.0.0.10/placement

[api]
auth_strategy = keystone

[keystone_authtoken]
auth_url = http://10.0.0.10:5000/v3
memcached_servers = 10.0.0.10:11211
auth_type = password
project_domain_name = Default
user_domain_name = Default
project_name = service
username = placement
password = placement
