# Compute Node - OVS 에이전트 설정
# 관리망(10.0.0.20)을 터널 엔드포인트로 사용하여 VXLAN 터널 구성

[ovs]
bridge_mappings = provider:br-provider
local_ip = 10.0.0.20

[agent]
tunnel_types = vxlan
l2_population = true

[securitygroup]
enable_security_group = true
firewall_driver = openvswitch
